language: node_js
os: osx
node_js:
  - "12"
  - "13"
branches:
  only:
  - master
  - release
before_install:
  - brew update-reset
  - brew cask install google-chrome
after_script:
  - npm run coverage
