/* eslint-disable comma-dangle */

/**
 * Declare keys with null values here.
 *
 * @returns {object} Keyed by organism ID.
 */
export default {
  window: null,
  document: null,
  '#patternlab-html': null,
  '#patternlab-body': null,
  '#sg-annotations': null,
  '#sg-annotations-container': null,
  '#sg-code-btn-markdown-cancel': null,
  '#sg-code-btn-markdown-edit': null,
  '#sg-code-btn-markdown-save': null,
  '#sg-code-code-language-markdown': null,
  '#sg-code-container': null,
  '#sg-code-fill': null, // DEPRECATED: Here for backward-compatibility.
  '#sg-code-input-git-off': null,
  '#sg-code-input-git-on': null,
  '#sg-code-lineage': null,
  '#sg-code-lineage-fill': null,
  '#sg-code-lineager': null,
  '#sg-code-lineager-fill': null,
  '#sg-code-missing-partials': null,
  '#sg-code-missing-partials-fill': null,
  '#sg-code-pane-git': null,
  '#sg-code-pane-git-na': null,
  '#sg-code-pane-markdown': null,
  '#sg-code-pane-markdown-edit': null,
  '#sg-code-pane-markdown-na': null,
  '#sg-code-panels': null,
  '#sg-code-panel-feplet': null,
  '#sg-code-panel-git': null,
  '#sg-code-panel-markdown': null,
  '#sg-code-panel-requerio': null,
  '#sg-code-pattern-info': null,
  '#sg-code-pattern-info-rel-path': null,
  '#sg-code-pattern-info-state': null,
  '#sg-code-pre-language-markdown': null,
  '#sg-code-tabs': null,
  '#sg-code-tab-feplet': null,
  '#sg-code-tab-git': null,
  '#sg-code-tab-markdown': null,
  '#sg-code-tab-requerio': null,
  '#sg-code-textarea-markdown': null,
  '#sg-controls': null,
  '#sg-cover': null,
  '#sg-f-toggle': null,
  '#sg-find': null,
  '#sg-form-label': null,
  '#sg-gen-container': null,
  '#sg-nav-message': null,
  '#sg-nav-target': null,
  '#sg-raw': null,
  '#sg-resize-btns': null,
  '#sg-rightpull': null,
  '#sg-size-disco': null,
  '#sg-size-em': null,
  '#sg-size-grow': null,
  '#sg-size-px': null,
  '#sg-size-random': null,
  '#sg-size-w': null,
  '#sg-t-annotations': null,
  '#sg-t-code': null,
  '#sg-t-toggle': null,
  '#sg-tools': null,
  '#sg-tools-toggle': null,
  '#sg-view': null,
  '#sg-view-btn-close': null,
  '#sg-view-btn-dock-left': null,
  '#sg-view-btn-dock-bottom': null,
  '#sg-view-btn-dock-right': null,
  '#sg-view-container': null,
  '#sg-viewport': null,
  '#sg-vp-wrap': null,
  '#typeahead': null,
  '.sg-acc-handle': null,
  '.sg-acc-panel': null,
  '.sg-code-panel': null,
  '.sg-code-tab': null,
  '.sg-nav-toggle': null,
  '.sg-pop': null,
  '.sg-size': null,
  '.sg-tool': null,
  '.sg-view-close-btn': null // DEPRECATED: Here for backward-compatibility.
};
