/* eslint-disable comma-dangle */

/**
 * Declare keys with null values here.
 *
 * @returns {object} Keyed by organism ID.
 */
export default {
  'window': null,
  'document': null,
  '#patternlab-html': null,
  '#patternlab-body': null,
  '#sg-annotations': null,
  '#sg-annotations-close-btn': null,
  '#sg-annotations-container': null,
  '#sg-code-close-btn': null,
  '#sg-code-container': null,
  '#sg-code-fill': null,
  '#sg-code-lineage': null,
  '#sg-code-lineage-fill': null,
  '#sg-code-lineager': null,
  '#sg-code-lineager-fill': null,
  '#sg-code-pattern-state': null,
  '#sg-code-pattern-state-fill': null,
  '#sg-code-title-html': null,
  '#sg-code-title-mustache': null,
  '#sg-controls': null,
  '#sg-cover': null,
  '#sg-f-toggle': null,
  '#sg-find': null,
  '#sg-form-label': null,
  '#sg-gen-container': null,
  '#sg-nav-message': null,
  '#sg-nav-target': null,
  '#sg-raw': null,
  '#sg-resize-btns': null,
  '#sg-rightpull': null,
  '#sg-size-disco': null,
  '#sg-size-em': null,
  '#sg-size-grow': null,
  '#sg-size-px': null,
  '#sg-size-random': null,
  '#sg-size-w': null,
  '#sg-t-annotations': null,
  '#sg-t-code': null,
  '#sg-t-toggle': null,
  '#sg-tools': null,
  '#sg-tools-toggle': null,
  '#sg-view': null,
  '#sg-viewport': null,
  '#sg-vp-wrap': null,
  '#typeahead': null,
  '.sg-acc-handle': null,
  '.sg-acc-panel': null,
  '.sg-code-title': null,
  '.sg-nav-toggle': null,
  '.sg-pop': null,
  '.sg-size': null,
  '.sg-tool': null,
};
