name: build

on:
  push:
    branches:
      - master
      - release

# fepper-ui is for the browser, not Node.js. Just test on GitHub Actions' default Node.js version.
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          brew update-reset
          brew install --cask google-chrome
          npm install
          npm run lint
          npm test
          npx nyc report --reporter=text-lcov > ./lcov.info

      - name: Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
