name: build

on:
  push:
    branches:
      - master
      - release

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version:
          - 12.x # fepper-ui is for the browser, not Node.js. Just test in the oldest supported LTS version.
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          brew update-reset
          brew cask install google-chrome
          npm install
          npm run lint
          npm test
          npx nyc report --reporter=text-lcov > ./lcov.info

      - name: Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
